### ISSUE TITLE
Test_thresh default value should be 0.5 for bias_test_check

### ISSUE THREAD

**Issue by wildcat47** [pymetrics/audit-ai#11]
It looks like the default value for the test_thresh parameter for the bias_test_check function should be 0.5 rather than 50.

**Comment by dwww2012** [comment]
is there anywhere in the code that breaks because of the default 50? i don't currently see any issue with that default, being that the `results` vector can be in (0,1) or (1, 100) or anything really

**Comment by wildcat47** [comment]
I found that was inconsistent with the instructions/example. predict_proba should give results in (0,1). That seems like the most likely workflow—is there a reason to assume users would provide results in (0,100)?
