### ISSUE TITLE
4/5 Test result doesn't show with logistic regression

### ISSUE THREAD

**Issue by janey5712** [pymetrics/audit-ai#20]
Hi there, thanks for sharing this package.

I got an issue when i applied the function with logistic regression. The 4/5 test result didn't show. Can you suggest what may cause this problem? Thanks!

![image](https://user-images.githubusercontent.com/46895615/67107302-2fc1d300-f19a-11e9-8f9f-e9b0a93024db.png)

**Comment by danieldiamond** [comment]
Hi @janey5712 thanks for sharing this issue and apologies in the delay. In your case you should pass in a `test_thresh` value through the function as the default value is causing all individuals to pass thus creating one dimensional contingency metrics. 

We had some discussion as to what the default `test_thresh` value should be, which I think might be of value you (see here https://github.com/pymetrics/audit-ai/pull/17#issuecomment-505210118).

Hope this helps!

**Comment by danieldiamond** [comment]
Closing for now. If issues still persist, feel free to provide more information and I'll take a look.
